force-app/main/default/objects/BC_Integration_Mapping__mdt/BC_Integration_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>BC Integration Mapping</label>
    <pluralLabel>BC Integration Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BC_Integration_Mapping__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <inlineHelpText>API Name of field to map</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BC_Integration_Mapping__mdt/fields/Insert_Only__c.field-meta.xml
<CustomField>
    <fullName>Insert_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Set to true if field should only be sent to Business Central on the initial sync and not continuously updated</inlineHelpText>
    <label>Insert Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BC_Integration_Mapping__mdt/fields/JSON_Key__c.field-meta.xml
<CustomField>
    <fullName>JSON_Key__c</fullName>
    <inlineHelpText>Key name in JSON request to which to map the Record Field</inlineHelpText>
    <label>JSON Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BCSyncUtils.cls
public with sharing class BCSyncUtils {

    public static Map<String, Object> buildRequestBody(SObject sObj, Object obj, List<BC_Integration_Mapping__mdt> lstFieldMappings, Boolean isInsert){ 
        //  convert object to Map<String, Object> and add in field mapping values. 
        Map<String, Object> mapObject = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(obj));
        if (lstFieldMappings != null) {
            
            for(BC_Integration_Mapping__mdt fieldMapping : lstFieldMappings){
                if(fieldMapping.Insert_Only__c && !isInsert){
                    continue;
                }
                mapObject.put(fieldMapping.Json_Key__c, sObj.get(fieldMapping.Field_Api_Name__c));
            }
        }
        return mapObject;
    }

}