force-app/main/default/objects/Customer_Product__c/Customer_Product__c.object-meta.xml
<CustomObject>
    <label>Customer Product</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Customer Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Product__c/fields/Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Portal_Access__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portal Access</label>
    <referenceTo>Portal_Access__c</referenceTo>
    <relationshipLabel>Customer Products</relationshipLabel>
    <relationshipName>Customer_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Customer Products</relationshipLabel>
    <relationshipName>Customer_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Access__c/Portal_Access__c.object-meta.xml
<CustomObject>
    <label>Portal Access</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Portal Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerProductDupeManagerFilterTest.cls
@isTest
private class CustomerProductDupeManagerFilterTest {
    
    private static final Integer RECORD_COUNT = 200;
    
    @isTest static void filterRecords_matchesCriteria_returnAll(){
        List<Customer_Product__c> lstCustProds = new List<Customer_Product__c>();
        for(Integer i=0; i<RECORD_COUNT;i++){
            lstCustProds.add(new Customer_Product__c(
            	Id = new TestUtils().generateDummyId(Customer_Product__c.SObjectType)
            	, Product__c = new TestUtils().generateDummyId(Product2.SObjectType)
            	, Portal_Access__c = new TestUtils().generateDummyId(Portal_Access__c.SObjectType)
            	, Active__c = true));
        }
        
        Test.startTest();
        
        List<Customer_Product__c> rLstCustProds = new CustomerProductDupeManagerFilter().filterRecords(lstCustProds);
        
        Test.stopTest();
        
        System.assertEquals(RECORD_COUNT, rLstCustProds.size());
    }
    
    @isTest static void filterRecords_inactive_returnNone(){
        List<Customer_Product__c> lstCustProds = new List<Customer_Product__c>();
        for(Integer i=0; i<RECORD_COUNT;i++){
            lstCustProds.add(new Customer_Product__c(
            	Id = new TestUtils().generateDummyId(Customer_Product__c.SObjectType)
            	, Product__c = new TestUtils().generateDummyId(Product2.SObjectType)
            	, Portal_Access__c = new TestUtils().generateDummyId(Portal_Access__c.SObjectType)
            	, Active__c = false));
        }
        
        Test.startTest();
        
        List<Customer_Product__c> rLstCustProds = new CustomerProductDupeManagerFilter().filterRecords(lstCustProds);
        
        Test.stopTest();
        
        System.assertEquals(0, rLstCustProds.size());
    }
}