force-app/main/default/objects/Customer_Product__c/Customer_Product__c.object-meta.xml
<CustomObject>
    <label>Customer Product</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Customer Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Product__c/fields/Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Portal_Access__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portal Access</label>
    <referenceTo>Portal_Access__c</referenceTo>
    <relationshipLabel>Customer Products</relationshipLabel>
    <relationshipName>Customer_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Customer Products</relationshipLabel>
    <relationshipName>Customer_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Access__c/Portal_Access__c.object-meta.xml
<CustomObject>
    <label>Portal Access</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Portal Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerProductDupeManagerFilter.cls
public with sharing class CustomerProductDupeManagerFilter {

    public List<Customer_Product__c> filterRecords(List<Customer_Product__c> lstCustProds){
        List<Customer_Product__c> lstFilteredRecords = new List<Customer_Product__c>();
        
        for(Customer_Product__c custProd : lstCustProds){
            if(custProd.Active__c && custProd.Product__c != null && custProd.Portal_Access__c != null){
                lstFilteredRecords.add(custProd);
            }
        }
        return lstFilteredRecords;
    }
}