force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Associated_Records__c.field-meta.xml
<CustomField>
    <fullName>Associated_Records__c</fullName>
    <label>Associated Records</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the error for reporting</description>
    <inlineHelpText>Category of the error for reporting</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>BigObjectException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
            <value>
                <fullName>SObjectException</fullName>
            </value>
            <value>
                <fullName>StringException</fullName>
            </value>
            <value>
                <fullName>TypeException</fullName>
            </value>
            <value>
                <fullName>VisualforceException</fullName>
            </value>
            <value>
                <fullName>XmlException</fullName>
            </value>
            <value>
                <fullName>CalloutResponse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>75768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/OpportunityBCSyncQueueable.cls
/**
 * @author CloudMasonry
 * @date 2021
 * @group Queueable
 * @description Enables async execution of OpportunityBCSyncCalloutService. Handles top level errors.
 */
public with sharing class OpportunityBCSyncQueueable implements Queueable, Database.AllowsCallouts {

    private Set<Id> setOppIds;
    private QueueableBatchManager batchManager;
    private static final Integer MAX_CALLOUTS_PER_RECORD = 2;

    public OpportunityBCSyncQueueable (Set<Id> setOppIds) {
        this(setOppIds, new QueueableBatchManager(QueueableBatchManager.Context.Callout, MAX_CALLOUTS_PER_RECORD));
    }

    @testVisible
    private OpportunityBCSyncQueueable(Set<Id> setOppIds, QueueableBatchManager batchManager){
        this.setOppIds = setOppIds;
        this.batchManager = batchManager;
        this.batchManager.setIds(setOppIds);
    }

    public void execute(QueueableContext context) {

        try {
            new OpportunityBCSyncCalloutService(this.batchManager.getBatchIds()).execute();
            if(!this.batchManager.getUnprocessedIds().isEmpty()){
                System.enqueueJob(new OpportunityBCSyncQueueable(this.batchManager.getUnprocessedIds()));
            }
        } catch (Exception ex){
            System.debug(ex.getMessage());
            System.debug(ex.getStackTraceString());
            insert new Error_Log__c(
            	Error_Message__c = ex.getMessage()
                , Stacktrace__c = ex.getStackTraceString()
                , Associated_Records__c = JSON.serialize(this.setOppIds)
                , Exception_Type__c = ex.getTypeName()
                , Category__c = OpportunityBCSyncCalloutService.EXCEPTION_CATEGORY
            );
        }
    }
}