force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Associated_Records__c.field-meta.xml
<CustomField>
    <fullName>Associated_Records__c</fullName>
    <label>Associated Records</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the error for reporting</description>
    <inlineHelpText>Category of the error for reporting</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>BigObjectException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
            <value>
                <fullName>SObjectException</fullName>
            </value>
            <value>
                <fullName>StringException</fullName>
            </value>
            <value>
                <fullName>TypeException</fullName>
            </value>
            <value>
                <fullName>VisualforceException</fullName>
            </value>
            <value>
                <fullName>XmlException</fullName>
            </value>
            <value>
                <fullName>CalloutResponse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SObjectDAO.cls
public with sharing class SObjectDAO {

    private List<SObject> lstSObjs;
    @testVisible
    private List<Database.SaveResult> lstSaveResult;

    public List<SObject> insertRecords(List<SObject> lstSObjs){
        Database.insert(lstSObjs, true);
        return lstSObjs;
    }

    public List<SObject> updateRecords(List<SObject> lstSObjs){

        return updateRecords(lstSObjs, true, false, null);
    }

    public List<SObject> updateRecordsAllowPartialSuccess(List<SObject> lstSObjs){

        return updateRecords(lstSObjs, false, false, null);
    }

    public List<SObject> updateRecordsAndLogErrors(List<SObject> lstSObjs, String strErrorCategory){

        return updateRecords(lstSObjs, false, true, strErrorCategory);
    }

    public List<SObject> updateRecords(List<SObject> lstSObjs, Boolean allOrNone, Boolean logErrors, String strErrorCategory){

        this.lstSObjs = lstSObjs;
        this.lstSaveResult = Database.update(lstSObjs, allOrNone);
        
        if(logErrors){
            logSaveResultErrors(strErrorCategory);
        }

        return lstSObjs;
    }

    public List<Database.SaveResult> getSaveResult(){
        return this.lstSaveResult;
    }

    public void logSaveResultErrors(String strErrorCategory){
        List<Error_Log__c> lstErrorLogs = new List<Error_Log__c>();

        if(this.lstSaveResult != null){

            for(Integer i=0; i < this.lstSaveResult.size(); i++){
                
                Database.SaveResult sr = this.lstSaveResult[i];
                SObject sObj = this.lstSObjs[i];

                if(!sr.isSuccess()){

                    String strErrorMsgs = '';
                    for(Database.Error err : sr.getErrors()){
                        strErrorMsgs += err.getStatusCode() + ': ' + err.getMessage() + '\r\n';
                    }
                    Error_Log__c errorLog = new Error_Log__c(
                        Associated_Records__c = sObj.Id
                        , Exception_Type__c = new DmlException().getTypeName()
                        , Category__c = strErrorCategory
                        , Error_Message__c = strErrorMsgs
                    );
                    lstErrorLogs.add(errorLog);
                }
            }
            if(!lstErrorLogs.isEmpty()){
                insert lstErrorLogs;
            }
        }
    }

}