force-app/main/default/objects/Associated_Training_Contacts__c/Associated_Training_Contacts__c.object-meta.xml
<CustomObject>
    <label>Associated Training Contact</label>
    <nameField>
        <displayFormat>ATC-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Training Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Contact__r.Account.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Training Contacts</relationshipLabel>
    <relationshipName>Training_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Contact_Email_for_GetFeedback__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_for_GetFeedback__c</fullName>
    <label>Contact Email for GetFeedback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/First_Name_Feedback__c.field-meta.xml
<CustomField>
    <fullName>First_Name_Feedback__c</fullName>
    <formula>Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name - Feedback</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Internal_Notes__c.field-meta.xml
<CustomField>
    <fullName>Internal_Notes__c</fullName>
    <label>Internal Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Last_Name_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_Feedback__c</fullName>
    <formula>Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name - Feedback</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Material_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Material_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Associated Training Contacts (Material Opportunity)</relationshipLabel>
    <relationshipName>Associated_Training_Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Materials_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Materials_Delivered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Materials Delivered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <label>Order No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/prework_task_status__c.field-meta.xml
<CustomField>
    <fullName>prework_task_status__c</fullName>
    <label>Prework Task Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Project_Grouping__c.field-meta.xml
<CustomField>
    <fullName>Project_Grouping__c</fullName>
    <label>Project Grouping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Team 1</fullName>
            </value>
            <value>
                <fullName>Team 2</fullName>
            </value>
            <value>
                <fullName>Team 3</fullName>
            </value>
            <value>
                <fullName>Team 4</fullName>
            </value>
            <value>
                <fullName>Team 5</fullName>
            </value>
            <value>
                <fullName>Team 6</fullName>
            </value>
            <value>
                <fullName>Team 7</fullName>
            </value>
            <value>
                <fullName>Team 8</fullName>
            </value>
            <value>
                <fullName>Team 9</fullName>
            </value>
            <value>
                <fullName>Team 10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Registered - wanting to move</fullName>
            </value>
            <value>
                <fullName>Pending - Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Pending - Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Scheduled to Attend</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Partially Attended</fullName>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>3</label>
            </value>
            <value>
                <fullName>Atended</fullName>
                <isActive>false</isActive>
                <label>Atended</label>
            </value>
            <value>
                <fullName>Atteneded</fullName>
                <isActive>false</isActive>
                <label>Atteneded</label>
            </value>
            <value>
                <fullName>Awaiting Payment</fullName>
                <isActive>false</isActive>
                <label>Awaiting Payment</label>
            </value>
            <value>
                <fullName>Certfied</fullName>
                <isActive>false</isActive>
                <label>Certfied</label>
            </value>
            <value>
                <fullName>Certifed</fullName>
                <isActive>false</isActive>
                <label>Certifed</label>
            </value>
            <value>
                <fullName>Certifield</fullName>
                <isActive>false</isActive>
                <label>Certifield</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>ITEM insert</fullName>
                <isActive>false</isActive>
                <label>ITEM insert</label>
            </value>
            <value>
                <fullName>Invited</fullName>
                <isActive>false</isActive>
                <label>Invited</label>
            </value>
            <value>
                <fullName>Logistics Contact</fullName>
                <isActive>false</isActive>
                <label>Logistics Contact</label>
            </value>
            <value>
                <fullName>No show</fullName>
                <isActive>false</isActive>
                <label>No show</label>
            </value>
            <value>
                <fullName>Not Certified</fullName>
                <isActive>false</isActive>
                <label>Not Certified</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Schedueld to attend</fullName>
                <isActive>false</isActive>
                <label>Schedueld to attend</label>
            </value>
            <value>
                <fullName>Schedueled to Attend</fullName>
                <isActive>false</isActive>
                <label>Schedueled to Attend</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <isActive>false</isActive>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Scheduled to Attended</fullName>
                <isActive>false</isActive>
                <label>Scheduled to Attended</label>
            </value>
            <value>
                <fullName>Scheled to Attend</fullName>
                <isActive>false</isActive>
                <label>Scheled to Attend</label>
            </value>
            <value>
                <fullName>Scheuled to attend</fullName>
                <isActive>false</isActive>
                <label>Scheuled to attend</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Training_Event__c.field-meta.xml
<CustomField>
    <fullName>Training_Event__c</fullName>
    <label>Training Event</label>
    <referenceTo>Training_Event__c</referenceTo>
    <relationshipLabel>Associated Training Contacts</relationshipLabel>
    <relationshipName>Training_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <label>Order No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Training_Event__c.field-meta.xml
<CustomField>
    <fullName>Training_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Event</label>
    <referenceTo>Training_Event__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Event__c/Training_Event__c.object-meta.xml
<CustomObject>
    <label>Training Event</label>
    <nameField>
        <label>Training Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirming Instructor</fullName>
            </value>
            <value>
                <fullName>Instructor Confirmed</fullName>
            </value>
            <value>
                <fullName>Confirming Training Mgr</fullName>
            </value>
            <value>
                <fullName>Confirming 2nd Training Mgr</fullName>
            </value>
            <value>
                <fullName>Confirming Co-Teach Instructor</fullName>
            </value>
            <value>
                <fullName>Co-Teach Confirmed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not available</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Confirming Resource Type 1</fullName>
            </value>
            <value>
                <fullName>Confirming Resource Type 2</fullName>
            </value>
            <value>
                <fullName>Confirming Resource Type 3</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Converted to VILT</fullName>
            </value>
            <value>
                <fullName>Confirming Back-up Instructor</fullName>
            </value>
            <value>
                <fullName>Back-up Instructor Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssociatedTrainingContactService.cls
public with sharing class AssociatedTrainingContactService {

    @AuraEnabled
    public static List<Associated_Training_Contacts__c> getDataByTrainingEventId(Id trainingEventId){
        return [
            SELECT 
                Id, 
                Training_Event__c, 
                Name, 
                First_Name_Feedback__c, 
                Last_Name_Feedback__c, 
                Contact_Email_for_GetFeedback__c, 
                Account_Name__c, 
                Status__c, 
                Internal_Notes__c, 
                prework_task_status__c, 
                Project_Grouping__c, 
                Material_Opportunity__c, 
                Material_Opportunity__r.Name,
                Materials_Delivered__c,
                Contact__c,
                Order_No__c,
                Contact__r.AccountId
            FROM Associated_Training_Contacts__c
            WHERE Training_Event__c = :trainingEventId
        ];
    }

}