force-app/main/default/objects/Associated_Training_Contacts__c/Associated_Training_Contacts__c.object-meta.xml
<CustomObject>
    <label>Associated Training Contact</label>
    <nameField>
        <displayFormat>ATC-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Training Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Training Contacts</relationshipLabel>
    <relationshipName>Training_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Training_Event__c.field-meta.xml
<CustomField>
    <fullName>Training_Event__c</fullName>
    <label>Training Event</label>
    <referenceTo>Training_Event__c</referenceTo>
    <relationshipLabel>Associated Training Contacts</relationshipLabel>
    <relationshipName>Training_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Event__c/Training_Event__c.object-meta.xml
<CustomObject>
    <label>Training Event</label>
    <nameField>
        <label>Training Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Event__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Program Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>TTT - Level 1</fullName>
            </value>
            <value>
                <fullName>TTT - Level 2</fullName>
            </value>
            <value>
                <fullName>ECM Boot Camp</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Custom-Training</fullName>
            </value>
            <value>
                <fullName>Custom-Advisory Services</fullName>
            </value>
            <value>
                <fullName>Delivering Project Results Workshop</fullName>
            </value>
            <value>
                <fullName>Speaking Engagement</fullName>
            </value>
            <value>
                <fullName>Practitioner</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Integrating Agile</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Methodology Application Program</fullName>
            </value>
            <value>
                <fullName>Leading Your Team Through Change</fullName>
            </value>
            <value>
                <fullName>Taking Charge of Change</fullName>
            </value>
            <value>
                <fullName>On Call</fullName>
            </value>
            <value>
                <fullName>Improve Project Health</fullName>
            </value>
            <value>
                <fullName>ADKAR Model Mastery Level 1: Prevent Change Resistance</fullName>
            </value>
            <value>
                <fullName>ADKAR Model Mastery Level 2: Resolve Change Barriers</fullName>
            </value>
            <value>
                <fullName>Achieve Change Performance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Event__c/fields/Type_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Event__c</fullName>
    <inlineHelpText>ONSITE means Enterprise Event. We are currently in process of upgrading the picklist values.</inlineHelpText>
    <label>Type of Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Public Partnership</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>On Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssociatedTrainingContactServiceTest.cls
@isTest
public with sharing class AssociatedTrainingContactServiceTest {

    @isTest
    public static void getAssociatedTrainingContactsByTrainingId() {

        Account testAccount = new Account();
        testAccount.Name = 'TestAccount';
        insert testAccount;

        Contact testContact = new Contact();
        testContact.FirstName = 'Test';
        testContact.LastName = 'Test';
        testContact.AccountId = testAccount.Id;
        insert testContact;

        Training_Event__c testTrainingEvent = new Training_Event__c();
        testTrainingEvent.Name = 'Test Training Event';
        testTrainingEvent.Type_of_Event__c = 'Test Event';
        testTrainingEvent.Title__c = 'Test Title';
        testTrainingEvent.Start_Date__c = Date.today();
        testTrainingEvent.Start_Date__c = Date.today().addMonths(1);
        insert testTrainingEvent;

        List<Training_Event__c> lstTE = [SELECT Id, Name FROM Training_Event__c];
        List<Contact> lstCon = [SELECT Id, Name FROM Contact];

        Id testTrainingEventId = lstTE[0].Id;

        Associated_Training_Contacts__c testATC = new Associated_Training_Contacts__c();
        testATC.Training_Event__c = lstTE[0].Id;
        testATC.Contact__c = lstCon[0].Id;
        insert testATC;

        Test.startTest();

        List<Associated_Training_Contacts__c> res = AssociatedTrainingContactService.getDataByTrainingEventId(testTrainingEventId);

        Test.stopTest();

        System.assertEquals(1, res.size());
        System.assertEquals(testTrainingEventId, res[0].Training_Event__c);

    }
}