force-app/main/default/objects/Account/fields/Account_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_2__c</fullName>
    <label>Account Name 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_No__c.field-meta.xml
<CustomField>
    <fullName>Account_No__c</fullName>
    <displayFormat>A{000000}</displayFormat>
    <externalId>true</externalId>
    <label>Account No</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/BC_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>BC_Sync_Status__c</fullName>
    <description>Integration Status of record with Business Central</description>
    <inlineHelpText>Integration Status of record with Business Central</inlineHelpText>
    <label>BC Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BC_Synced__c.field-meta.xml
<CustomField>
    <fullName>BC_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if record is synced to BC system</description>
    <inlineHelpText>Record has been synced to Business Central</inlineHelpText>
    <label>BC Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NET 10</fullName>
            </value>
            <value>
                <fullName>NET 15</fullName>
            </value>
            <value>
                <fullName>NET 30</fullName>
            </value>
            <value>
                <fullName>NET 30 10D</fullName>
            </value>
            <value>
                <fullName>NET 45</fullName>
            </value>
            <value>
                <fullName>NET 60</fullName>
            </value>
            <value>
                <fullName>NET 75</fullName>
            </value>
            <value>
                <fullName>NET 90</fullName>
            </value>
            <value>
                <fullName>RECEIPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <inlineHelpText>RESELLER (Currently only Baker &amp; Taylor)
SERVICE (Currently only Microsoft)</inlineHelpText>
    <label>Price Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADKAR</fullName>
            </value>
            <value>
                <fullName>COMPLETE</fullName>
            </value>
            <value>
                <fullName>ECM</fullName>
            </value>
            <value>
                <fullName>MANAGER</fullName>
            </value>
            <value>
                <fullName>OCC</fullName>
            </value>
            <value>
                <fullName>AFFILIATE</fullName>
            </value>
            <value>
                <fullName>AFFTIER2</fullName>
            </value>
            <value>
                <fullName>ATP</fullName>
            </value>
            <value>
                <fullName>ATPTIER2</fullName>
            </value>
            <value>
                <fullName>RESELLER</fullName>
            </value>
            <value>
                <fullName>SERVICE</fullName>
            </value>
            <value>
                <fullName>PILOT</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>STDDISC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BC_Integration_Config__mdt/BC_Integration_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for each Business Central Integration</description>
    <label>BC Integration Config</label>
    <pluralLabel>BC Integration Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/BC_Integration_Config__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <inlineHelpText>Named Credential for the web service for authentication</inlineHelpText>
    <label>Named Credential</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business_Central_US</fullName>
                <default>true</default>
                <label>Business_Central_US</label>
            </value>
            <value>
                <fullName>Business_Central_CAN</fullName>
            </value>
            <value>
                <fullName>Business_Central_ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BC_Integration_Config__mdt/fields/URI_Path__c.field-meta.xml
<CustomField>
    <fullName>URI_Path__c</fullName>
    <inlineHelpText>URI path of the web service endpoint. Appends to the URL in the Named Credential.</inlineHelpText>
    <label>URI Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BC_Integration_Mapping__mdt/BC_Integration_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>BC Integration Mapping</label>
    <pluralLabel>BC Integration Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BC_Integration_Mapping__mdt/fields/BC_Instance__c.field-meta.xml
<CustomField>
    <fullName>BC_Instance__c</fullName>
    <label>BC Instance</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business_Central_US</fullName>
                <default>true</default>
                <label>Business_Central_US</label>
            </value>
            <value>
                <fullName>Business_Central_CAN</fullName>
            </value>
            <value>
                <fullName>Business_Central_ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Associated_Records__c.field-meta.xml
<CustomField>
    <fullName>Associated_Records__c</fullName>
    <label>Associated Records</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/BC_Instance__c.field-meta.xml
<CustomField>
    <fullName>BC_Instance__c</fullName>
    <label>BC Instance</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BC_Synced_Instances_c</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the error for reporting</description>
    <inlineHelpText>Category of the error for reporting</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>BigObjectException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
            <value>
                <fullName>SObjectException</fullName>
            </value>
            <value>
                <fullName>StringException</fullName>
            </value>
            <value>
                <fullName>TypeException</fullName>
            </value>
            <value>
                <fullName>VisualforceException</fullName>
            </value>
            <value>
                <fullName>XmlException</fullName>
            </value>
            <value>
                <fullName>CalloutResponse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>75768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/BC_Synced_Instances_c.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business_Central_ANZ</fullName>
        <label>Business Central ANZ</label>
    </customValue>
    <customValue>
        <fullName>Business_Central_CAN</fullName>
        <label>Business Central CAN</label>
    </customValue>
    <customValue>
        <fullName>Business_Central_US</fullName>
        <label>Business Central US</label>
    </customValue>
    <description>BC Regions</description>
    <masterLabel>BC Synced Instances</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountBCSyncCalloutService.cls
/**
 * @author CloudMasonry
 * @date 2021
 * @group Web Service Callout Service
 * @description Performs callouts to Business Central to sync Account records
 */
public with sharing class AccountBCSyncCalloutService {

    @testVisible
    private static final String STATUS_SYNCED = 'Synced';
    @testVisible
    private static final String STATUS_FAILED = 'Failed';
    public static final String EXCEPTION_CATEGORY = 'Account BC Sync';
    // placeholder value to tell BC to write field as null
    // distinguishes from fields that are not included in payload that would otherwise appear blank
    @testVisible
    private static final String NULL_PLACEHOLDER = '-';
    // @testVisible
    public static final String INTEGRATION_CONFIG_NAME = 'SFCustomerEntries';
    private static final Integer REQ_TIME_OUT = 60000;
    @testVisible
    private static final String EXCEPTION_MISSING_CUSTOM_METADATA = 'No Active BC Integration Configuration for ';


    private static Set<String> queryFields = new Set<String>{
        'Name'    
        , 'Account_Name_2__c'
        , 'BillingStreet'
        , 'BillingCity'
        , 'BillingState'
        , 'BillingPostalCode'
        , 'BillingCountry'
        , 'Phone'
        , 'Fax'
        , 'Price_Group__c'
        , 'Payment_Terms__c'
        , 'Account_No__c'
        , 'BC_Synced_Instances__c'
        , 'BC_Synced__c'
    };
    @testVisible
    private BCSyncDAO serviceDAO;
    @testVisible
    private SObjectDAO sObjDAO; 
    @testVisible
    private Set<Id> setAcctIds;
    @testVisible
    List<Account> lstAcctsToUpdate;
    @testVisible
    List<Error_Log__c> lstErrorsToInsert;

    @testVisible
    private Map<String, BC_Integration_Config__mdt> integrationDetailsMap {
        get {
            if(integrationDetailsMap == null){
                integrationDetailsMap = serviceDAO.getIntegrationConfigMap(INTEGRATION_CONFIG_NAME);
            }
            return integrationDetailsMap;
        }
        set;
    }
    @testVisible
    private List<BC_Integration_Mapping__mdt> lstFieldMap {
        get {
            if(lstFieldMap == null){
                lstFieldMap = serviceDAO.getIntegrationFieldMapping(INTEGRATION_CONFIG_NAME);
            }
            return lstFieldMap;
        }
        set;
    }

    private Map<String, List<BC_Integration_Mapping__mdt>> integrationMapping {
        get {
            if(integrationMapping == null){
                integrationMapping = serviceDAO.buildIntegrationFieldMappingsMap(lstFieldMap);
            }
            return integrationMapping;
        }
        set;
    }

    /**
     * @description Class constructor
     * @param  setAcctIds Record Ids of accounts to sync
     */
    public AccountBCSyncCalloutService(Set<Id> setAcctIds){
        this(setAcctIds, new BCSyncDAO(), new SObjectDAO());
    }

    @testVisible
    private AccountBCSyncCalloutService(Set<Id> setAcctIds, BCSyncDAO serviceDAO, SObjectDAO sObjDAO){
        this.setAcctIds = setAcctIds;
        this.serviceDAO = serviceDAO;
        this.sObjDAO = sObjDAO;


    }

    /**
     * @description Executes callouts to Business Central for each account. Performs callout per Account and per active Instance Configuration
     *              Allows for individual accounts to fail.
     */
    public void execute(){
        if(this.setAcctIds.isEmpty()) { return; }

        this.lstAcctsToUpdate = new List<Account>();
        this.lstErrorsToInsert = new List<Error_Log__c>();

        List<Account> lstAccts = this.serviceDAO.getRecords('Account', queryFields, this.lstFieldMap, this.setAcctIds);
        for(Account acct : lstAccts){

            Integer successCount = 0;

            for(BC_Integration_Config__mdt bcInstance : integrationDetailsMap.values()){

                Boolean isSuccess = sendHTTPReqToInstance(acct, bcInstance);
                if(isSuccess){
                    successCount++;
                }
            }

            setRecordSyncStatus(acct, successCount == integrationDetailsMap.size());
        }

        saveRecords();
    }

    /**
     * @description Executes callouts to Business Central for each account. Performs callout per Account and the specified Instance Configuration
     *              Allows for individual accounts to fail.
     * @param  strBCInstance strBCInstance description
     */
    public void execute(String strBCInstance){
        if(this.setAcctIds.isEmpty()) { return; }

        this.lstAcctsToUpdate = new List<Account>();
        this.lstErrorsToInsert = new List<Error_Log__c>();

        List<Account> lstAccts = this.serviceDAO.getRecords('Account', queryFields, this.lstFieldMap, this.setAcctIds);

        BC_Integration_Config__mdt bcInstanceConfig = integrationDetailsMap.get(strBCInstance);

        if(bcInstanceConfig == null){
            throw new CustomMetadataException(EXCEPTION_MISSING_CUSTOM_METADATA + strBCInstance);
        }

        for(Account acct : lstAccts){
            Boolean isSuccess = sendHTTPReqToInstance(acct, bcInstanceConfig);

            setRecordSyncStatus(acct, isSuccess);
        }

        saveRecords();
    }

    private Boolean sendHTTPReqToInstance(Account acct, BC_Integration_Config__mdt bcInstanceConfig){
        Boolean isSuccess = false;
        String strJSONRequest;
    
        try {

            strJSONRequest = JSON.serialize(buildRequestBody(acct, bcInstanceConfig.Named_Credential__c));

            HTTPRequest req = new HTTPRequest();

            req.setTimeout(REQ_TIME_OUT);
            req.setBody(strJSONRequest);
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('Content-Length', '' + strJSONRequest.length());
            req.setHeader('Accept', 'application/json');
            req.setEndpoint('callout:' + bcInstanceConfig.Named_Credential__c + bcInstanceConfig.URI_Path__c);
            req.setMethod('POST');
            
            System.debug('REQUEST');
            System.debug(JSON.serializePretty(JSON.deserializeUntyped(strJSONRequest)));

            HTTP http = new HTTP();
            HTTPResponse res = http.send(req);

            System.debug('RESPONSE');
            System.debug(res);

            if (res.getStatusCode() == 201) {
                acct.BC_Synced_Instances__c = StringUtils.addMultiSelectPicklistValue(acct.BC_Synced_Instances__c, bcInstanceConfig.Named_Credential__c);
                System.debug(JSON.serializePretty(JSON.deserializeUntyped(res.getBody())));
                isSuccess = true;
            } else {
                throw new CalloutException(String.valueOf(res) + ' ' + res.getBody());
                
            }

        } catch (Exception ex){
            this.lstErrorsToInsert.add(new Error_Log__c(
                    Error_Message__c = ex.getMessage()
                    , Stacktrace__c = ex.getStackTraceString()
                    , Associated_Records__c = acct.Id
                    , Request_Body__c = strJSONRequest
                    , Exception_Type__c = ex.getTypeName()
                    , Category__c = EXCEPTION_CATEGORY
                    , BC_Instance__c = bcInstanceConfig.Named_Credential__c

                ));
            System.debug(' this is ex.getStackTraceString():' + ex.getStackTraceString());
            System.debug(' this is ex.getMessage():' + ex.getMessage());
            isSuccess = false;
        }
        return isSuccess;
    }

    private Map<String, Object> buildRequestBody (Account acct, String strBCInstance){
        Boolean isInsert = !(acct.BC_Synced_Instances__c != null && acct.BC_Synced_Instances__c.contains(strBCInstance));
        Object obj = isInsert ? (Object)new AccountInitSyncWrapper(acct) : (Object)new AccountSyncWrapper(acct);
        List<BC_Integration_Mapping__mdt> lstFieldMappings = integrationMapping.get(strBCInstance);
        return BCSyncUtils.buildRequestBody(acct, obj, lstFieldMappings, isInsert);
    }

    private void setRecordSyncStatus(Account acct, Boolean isSuccess){
        lstAcctsToUpdate.add(new Account(
            Id = acct.Id
            , BC_Synced_Instances__c = acct.BC_Synced_Instances__c
            , BC_Sync_Status__c = isSuccess ? STATUS_SYNCED : STATUS_FAILED
            , BC_Synced__c = isSuccess ? true : acct.BC_Synced__c
            )
        );
    }

    /**
     * @description saveRecords description
     */
    private void saveRecords(){
        this.sObjDAO.updateRecords(this.lstAcctsToUpdate);
        if(!this.lstErrorsToInsert.isEmpty()){
            this.sObjDAO.insertRecords(this.lstErrorsToInsert);
        }
    }
    
    /**
     * @description Base Wrapper class to construct payload to Business Central (BC)
     *              Includes fields synced in all scenarios, initial and continuous sync to BC
     *              Virtual class to allow extension for different sync scenarios and payloads
     */
    public virtual class AccountSyncWrapper {
        String SF_Record_ID { get; set; }
        String SF_Customer_ID { get; set; }
        String Name { get; set; }
        String Name_2 { get; set; }
        String Customer_Price_Group { get; set; }
        String Payment_Terms_Code { get; set; }

        
        public AccountSyncWrapper(Account acct) {
            this.SF_Record_ID = acct.Id;
            this.SF_Customer_ID = String.isEmpty(acct.Account_No__c) ? NULL_PLACEHOLDER : acct.Account_No__c;
            this.Name = String.isEmpty(acct.Name) ? NULL_PLACEHOLDER : acct.Name;
            this.Name_2 = String.isEmpty(acct.Account_Name_2__c) ? NULL_PLACEHOLDER : acct.Account_Name_2__c;
            this.Customer_Price_Group = String.isEmpty(acct.Price_Group__c) ? NULL_PLACEHOLDER : acct.Price_Group__c;
            this.Payment_Terms_Code = String.isEmpty(acct.Payment_Terms__c) ? NULL_PLACEHOLDER : acct.Payment_Terms__c;

        }
        
    }

    /**
     * @description Wrapper class to constructor payload to Business Central (BC)
     *              Extends base wrapper to add fields that are sent only on the initial sync to BC
     */
    public class AccountInitSyncWrapper extends AccountSyncWrapper {
        @TestVisible
        String Address { get; set; }
        @TestVisible
       	String Address_2 { get; set; }
        String Country_Region { get; set; }
        String City { get; set; }
        String County { get; set; }
        String Post_Code { get; set; }
        String Phone_No { get; set; }
        String Fax_No { get; set; }
        
        public AccountInitSyncWrapper(Account acct) {
            super(acct);
            if (String.isBlank(acct.BillingStreet)) {
                this.Address = NULL_PLACEHOLDER;
                this.Address_2 = NULL_PLACEHOLDER;
            } else {
                List<String> streetLines = acct.BillingStreet.split('\r\n');
                this.Address = streetLines.get(0);
                this.Address_2 = streetLines.size() == 1 ? NULL_PLACEHOLDER : streetLines.get(1);
            }
           	this.Country_Region = String.isEmpty(acct.BillingCountry) ? NULL_PLACEHOLDER : acct.BillingCountry;
            this.City = String.isEmpty(acct.BillingCity) ? NULL_PLACEHOLDER : acct.BillingCity;
            this.County = String.isEmpty(acct.BillingState) ? NULL_PLACEHOLDER : acct.BillingState;
            this.Post_Code = String.isEmpty(acct.BillingPostalCode) ? NULL_PLACEHOLDER : acct.BillingPostalCode;
            this.Phone_No = String.isEmpty(acct.Phone) ? NULL_PLACEHOLDER : acct.Phone;
            this.Fax_No = String.isEmpty(acct.Fax) ? NULL_PLACEHOLDER : acct.Fax;
        }
    }
}