force-app/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the account manager on record</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Account Manager)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACTIVITIES TO SUPPORT MINERAL EXTRACTION</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATIVE ACTIVITIES, COMPLEMENTARY SERVICES AND CONSULTING</fullName>
            </value>
            <value>
                <fullName>ADVERTISING AND MARKET RESEARCH</fullName>
            </value>
            <value>
                <fullName>Aerospace/Aviation</fullName>
            </value>
            <value>
                <fullName>Agriculture, Forestry, Fishing &amp; Hunting</fullName>
            </value>
            <value>
                <fullName>AGRICULTURE, LIVESTOCK / POULTRY AND RELATED SERVICES</fullName>
            </value>
            <value>
                <fullName>Arts, Entertainment &amp; Recreation</fullName>
            </value>
            <value>
                <fullName>AUTOMOTIVE MANUFACTURE OF, TRAILERS AND CARTS</fullName>
            </value>
            <value>
                <fullName>Chemical Manufacturing</fullName>
            </value>
            <value>
                <fullName>COMMUNICATION</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>DEFENSE AND SOCIAL SECURITY</fullName>
            </value>
            <value>
                <fullName>Development and Manufacturing</fullName>
            </value>
            <value>
                <fullName>EDUCATION</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Energy, Oil, &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>EXTRACTION OF METALLIC MINERALS</fullName>
            </value>
            <value>
                <fullName>EXTRACTION OF MINERAL COAL</fullName>
            </value>
            <value>
                <fullName>EXTRACTION OF NON-METALLIC MINERALS</fullName>
            </value>
            <value>
                <fullName>EXTRACTION OF PETROLEUM AND NATURAL GAS</fullName>
            </value>
            <value>
                <fullName>FABRICATION OF FURNITURE</fullName>
            </value>
            <value>
                <fullName>Fast Moving Consumer Goods</fullName>
            </value>
            <value>
                <fullName>Finance/Banking</fullName>
            </value>
            <value>
                <fullName>FINANCIAL ACTIVITIES, INSURANCE AND RELATED SERVICES</fullName>
            </value>
            <value>
                <fullName>FISHERIES AND AQUACULTURE</fullName>
            </value>
            <value>
                <fullName>FOOD</fullName>
            </value>
            <value>
                <fullName>Food/Beverage</fullName>
            </value>
            <value>
                <fullName>FOREST PRODUCTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <formula>Account.Account_Manager__r.FirstName + &quot; &quot; +  Account.Account_Manager__r.LastName</formula>
    <label>Account Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/industry__c.field-meta.xml
<CustomField>
    <fullName>industry__c</fullName>
    <formula>TEXT(Account.Industry__c)</formula>
    <label>industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>pse__Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GlobalGrowth_AccountManagerBatchTest.cls
/***********************************************************************************************************************        
Name            : GlobalGrowth_AccountManagerBatch
Author          : Slalom Team, Reggie Thompson
Date            : 07/16/24
@description    : Test class for CS_HealthCheckBatch[Helper]
***********************************************************************************************************************/
@IsTest
private class GlobalGrowth_AccountManagerBatchTest {

    @testSetup
    static void setupData() {
        List<Account> testAccounts = new List<Account>();
        for (Integer i = 0; i < 200; i++) {
            Account testAccount = new Account(
                name = 'Test Account ' + i,
                Industry__c = ,
                CurrencyIsoCode = 'USD'
            );

            testAccounts.add(testAccount);
        }

        insert testAccounts;

        List<User> testUsers = new List<User>();
        Profile testSysAdminId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        for (Integer i = 0; i < 200; i++) {
            User testUser = new User(
                CurrencyIsoCode = 'USD',
                IsActive = true,
                Alias = 'tU' + i,
                SenderEmail = 'testUser' + i + '@example.com',
                EmailEncodingKey = 'UTF-8',
                FirstName = 'Test',
                LastName = 'User ' + i,
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = testSysAdminId.Id,
                TimeZonesIdKey = 'America/Denver',
                UserName = email
            );

            testUsers.add(testUser);
        }

        insert testUsers;

        List<Contact> testContacts = new List<Contact>();
        for (Account testAccount : testAccounts) {
            Integer i = 0;

            List<Contact> testContact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact',
                AccountId = testAccounts[i],
                CurrencyIsoCode = 'USD',
                pse__Salesforce_User__c = testUsers[i]
            );

            testContacts.add(testContact);
            i++;
        }

        insert testContacts;

        for (Account testAccount : testAccounts) {
            Integer i = 0;

            testAccount.Account_Manager__c = testContacts[i].Id;
        }

        update testAccounts;
    }

    // @isTest
    // static void testAccountManagerSync() {

    //     Test.startTest();
    //     GlobalGrowth_AccountManagerBatch batch = new GlobalGrowth_AccountManagerBatch();
    //     Database.executeBatch(batch);
    //     Test.stopTest();
    // }
}