force-app/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the account manager on record</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Account Manager)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/account_manager_email__c.field-meta.xml
<CustomField>
    <fullName>account_manager_email__c</fullName>
    <label>Account Manager Email</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_email_domain__c.field-meta.xml
<CustomField>
    <fullName>Company_email_domain__c</fullName>
    <description>Enter everything after the &quot;@&quot;.  This field is used in the mapping process of registration importing, specifically at this time for HQ.</description>
    <inlineHelpText>Enter everything after the &quot;@&quot;.  This field is used in the mapping process of registration importing, specifically at this time for HQ.</inlineHelpText>
    <label>Company email domain</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/GAN_Lead_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>GAN_Lead_Notification_Email__c</fullName>
    <inlineHelpText>This is the email address for the GAN Contact that leads get sent to.</inlineHelpText>
    <label>GAN Lead Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACTIVITIES TO SUPPORT MINERAL EXTRACTION</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATIVE ACTIVITIES, COMPLEMENTARY SERVICES AND CONSULTING</fullName>
            </value>
            <value>
                <fullName>ADVERTISING AND MARKET RESEARCH</fullName>
            </value>
            <value>
                <fullName>Aerospace/Aviation</fullName>
            </value>
            <value>
                <fullName>Agriculture, Forestry, Fishing &amp; Hunting</fullName>
            </value>
            <value>
                <fullName>AGRICULTURE, LIVESTOCK / POULTRY AND RELATED SERVICES</fullName>
            </value>
            <value>
                <fullName>Arts, Entertainment &amp; Recreation</fullName>
            </value>
            <value>
                <fullName>AUTOMOTIVE MANUFACTURE OF, TRAILERS AND CARTS</fullName>
            </value>
            <value>
                <fullName>Chemical Manufacturing</fullName>
            </value>
            <value>
                <fullName>COMMUNICATION</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>DEFENSE AND SOCIAL SECURITY</fullName>
            </value>
            <value>
                <fullName>Development and Manufacturing</fullName>
            </value>
            <value>
                <fullName>EDUCATION</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Energy, Oil, &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>EXTRACTION OF METALLIC MINERALS</fullName>
            </value>
            <value>
                <fullName>EXTRACTION OF MINERAL COAL</fullName>
            </value>
            <value>
                <fullName>EXTRACTION OF NON-METALLIC MINERALS</fullName>
            </value>
            <value>
                <fullName>EXTRACTION OF PETROLEUM AND NATURAL GAS</fullName>
            </value>
            <value>
                <fullName>FABRICATION OF FURNITURE</fullName>
            </value>
            <value>
                <fullName>Fast Moving Consumer Goods</fullName>
            </value>
            <value>
                <fullName>Finance/Banking</fullName>
            </value>
            <value>
                <fullName>FINANCIAL ACTIVITIES, INSURANCE AND RELATED SERVICES</fullName>
            </value>
            <value>
                <fullName>FISHERIES AND AQUACULTURE</fullName>
            </value>
            <value>
                <fullName>FOOD</fullName>
            </value>
            <value>
                <fullName>Food/Beverage</fullName>
            </value>
            <value>
                <fullName>FOREST PRODUCTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/Associated_Training_Contacts__c.object-meta.xml
<CustomObject>
    <label>Associated Training Contact</label>
    <nameField>
        <displayFormat>ATC-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Training Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/ATC_Email__c.field-meta.xml
<CustomField>
    <fullName>ATC_Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ATC Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Training Contacts</relationshipLabel>
    <relationshipName>Training_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Contact_Email_for_GetFeedback__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_for_GetFeedback__c</fullName>
    <label>Contact Email for GetFeedback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Email_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Email_Feedback__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email - Feedback</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/portal_access__c.field-meta.xml
<CustomField>
    <fullName>portal_access__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Portal Access</label>
    <referenceTo>Portal_Access__c</referenceTo>
    <relationshipLabel>Associated Training Contacts</relationshipLabel>
    <relationshipName>Associated_Training_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Survey_Resend_Email_for_GetFeedback__c.field-meta.xml
<CustomField>
    <fullName>Survey_Resend_Email_for_GetFeedback__c</fullName>
    <inlineHelpText>Enter the email address the attendee wants the survey resent to</inlineHelpText>
    <label>Survey Resend Email for GetFeedback</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Associated_Training_Contacts__c/fields/Training_Event__c.field-meta.xml
<CustomField>
    <fullName>Training_Event__c</fullName>
    <label>Training Event</label>
    <referenceTo>Training_Event__c</referenceTo>
    <relationshipLabel>Associated Training Contacts</relationshipLabel>
    <relationshipName>Training_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <formula>Account.Account_Manager__r.FirstName + &quot; &quot; +  Account.Account_Manager__r.LastName</formula>
    <label>Account Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/industry__c.field-meta.xml
<CustomField>
    <fullName>industry__c</fullName>
    <formula>TEXT(Account.Industry__c)</formula>
    <label>industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Leader_Email__c.field-meta.xml
<CustomField>
    <fullName>Leader_Email__c</fullName>
    <label>Leader Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/P_Secondary_Email__c.field-meta.xml
<CustomField>
    <fullName>P_Secondary_Email__c</fullName>
    <label>Secondary Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Portal_Access__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portal Access</label>
    <referenceTo>Portal_Access__c</referenceTo>
    <relationshipLabel>Contact</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>pse__Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Reports_To_Email__c.field-meta.xml
<CustomField>
    <fullName>Reports_To_Email__c</fullName>
    <label>Reports To Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email__c</fullName>
    <label>Secondary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Email_Address_2__c</fullName>
    <label>Email_Address_2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Address_3__c.field-meta.xml
<CustomField>
    <fullName>Email_Address_3__c</fullName>
    <label>Email_Address_3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email_Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Portal_Access__c/Portal_Access__c.object-meta.xml
<CustomObject>
    <label>Portal Access</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Portal Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Access__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portal Access</relationshipLabel>
    <relationshipName>Portal_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Access__c/fields/customer_type_id__c.field-meta.xml
<CustomField>
    <fullName>customer_type_id__c</fullName>
    <inlineHelpText>1 - Direct
2 - License Admin
3 - License User
4 - Enterprise Program Participant</inlineHelpText>
    <label>Customer Type ID</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Access__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Access__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Access__c/fields/Unique_Email__c.field-meta.xml
<CustomField>
    <fullName>Unique_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Training_Event__c/Training_Event__c.object-meta.xml
<CustomObject>
    <label>Training Event</label>
    <nameField>
        <label>Training Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Event__c/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <formula>End_User_Company__r.Account_Manager__r.FirstName + &quot; &quot; +  End_User_Company__r.Account_Manager__r.LastName</formula>
    <label>Account Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SandboxPostRefreshScriptTest.cls
@isTest
class SandboxPostRefreshScriptTest {

    @isTest
    static void testMySandboxPostRefresh() {
        // Insert logic here to create records of the objects that the class you’re testing manipulates.
        Account testAccount = new Account(
            Name = 'Test Account',
            Industry__c = 'Consulting',
            CurrencyIsoCode = 'USD',
            account_manager_email__c = 'test@prosci.com',
            Company_email_domain__c = 'prosci.com',
            GAN_Lead_Notification_Email__c	= 'test@prosci.com'
        );
        insert testAccount;

        Profile testSysAdminId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

        User testUser = new User(
            CurrencyIsoCode = 'USD',
            IsActive = true,
            Alias = 'tU',
            Email = 'testUser@prosci.com',
            EmailEncodingKey = 'UTF-8',
            FirstName = 'Test',
            LastName = 'User',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = testSysAdminId.Id,
            TimeZonesIdKey = 'America/Denver',
            UserName = 'userTest@prosci.com'
        );

        insert testUser;

        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = testAccount.Id,
            CurrencyIsoCode = 'USD',
            pse__Salesforce_User__c = testUser.Id,
            Email = 'test@prosci.com',
            Leader_Email__c = 'test@prosci.com',
            Reports_To_Email__c = 'test@prosci.com',
            Secondary_Email__c = 'test@prosci.com',
            P_Secondary_Email__c = 'test@prosci.com'
        );

        insert testContact;

        testAccount.Account_Manager__c = testContact.Id;
        update testAccount;

        Lead testLead = new Lead(
            FirstName = 'Test',
            LastName = 'Lead',
            Company = 'Prosci',
            Email = 'test@prosci.com',
            Email_Address__c = 'test@prosci.com',
            Email_Address_2__c = 'test@prosci.com',
            Email_Address_3__c = 'test@prosci.com'
        );

        insert testLead;

        Training_Event__c testTrainingEvent = new Training_Event__c(
            Name = 'Test Event'
        );

        insert testTrainingEvent;

        Associated_Training_Contacts__c testTrainingContact = new Associated_Training_Contacts__c(
            Contact__c = testContact.Id, // sets the email text formula fields ATC_Email__c and Email_Feedback__c
            Contact_Email_for_GetFeedback__c = 'test@prosci.com',
            Survey_Resend_Email_for_GetFeedback__c = 'test@prosci.com',
            Training_Event__c = testTrainingEvent.Id
        );

        insert testTrainingContact;

        Portal_Access__c testPortalAccess = new Portal_Access__c(
            First_Name__c = 'test',
            Last_Name__c = 'portal access',
            customer_type_id__c = '1',
            Email__c ='test@prosci.com',
            Unique_Email__c ='testunique@prosci.com'
        );

        insert testPortalAccess;

        Test.startTest();

        //Execute test script with RunAsAutoProcUser set to true
        Test.testSandboxPostCopyScript(
            new SandboxPostRefreshScript(), 
            UserInfo.getOrganizationId(),
            UserInfo.getOrganizationId(),
            UserInfo.getOrganizationName(),
            true
        );

        Test.stopTest();

        // Insert assert statements here to check that the records you created above have invalidated email addresses
        testAccount = [
            SELECT
                account_manager_email__c, 
                Company_email_domain__c, 
                GAN_Lead_Notification_Email__c
            FROM Account
            WHERE Id = :testAccount.Id
        ];

        Assert.isTrue(testAccount.account_manager_email__c.endsWith('.invalid'),'Account.account_manager_email__c is invalidated');
        Assert.isTrue(testAccount.Company_email_domain__c.endsWith('.invalid'),'Account.Company_email_domain__c is invalidated');
        Assert.isTrue(testAccount.GAN_Lead_Notification_Email__c.endsWith('.invalid'),'Account.GAN_Lead_Notification_Email__c is invalidated');

        testContact = [
            SELECT
                Email,
                Leader_Email__c,
                Reports_To_Email__c,
                Secondary_Email__c,
                P_Secondary_Email__c
            FROM Contact
            WHERE Id = :testContact.Id
        ];

        Assert.isTrue(testContact.Email.endsWith('.invalid'),'Contact.Email is invalidated');
        Assert.isTrue(testContact.Leader_Email__c.endsWith('.invalid'),'Contact.Leader_Email__c is invalidated');
        Assert.isTrue(testContact.Reports_To_Email__c.endsWith('.invalid'),'Contact.Reports_To_Email__c is invalidated');
        Assert.isTrue(testContact.Secondary_Email__c.endsWith('.invalid'),'Contact.Secondary_Email__c is invalidated');
        Assert.isTrue(testContact.P_Secondary_Email__c.endsWith('.invalid'),'Contact.P_Secondary_Email__c is invalidated');

        testLead = [
            SELECT
                Email,
                Email_Address__c,
                Email_Address_2__c,
                Email_Address_3__c
            FROM Lead
            WHERE Id = :testLead.Id
        ];

        Assert.isTrue(testLead.Email.endsWith('.invalid'),'Lead.Email is invalidated');
        Assert.isTrue(testLead.Email_Address__c.endsWith('.invalid'),'Lead.Email_Address__c is invalidated');
        Assert.isTrue(testLead.Email_Address_2__c.endsWith('.invalid'),'Lead.Email_Address_2__c is invalidated');
        Assert.isTrue(testLead.Email_Address_3__c.endsWith('.invalid'),'Lead.Email_Address_3__c is invalidated');

        testTrainingContact = [
            SELECT
                Contact_Email_for_GetFeedback__c,
                Survey_Resend_Email_for_GetFeedback__c
            FROM Associated_Training_Contacts__c
            WHERE Id = :testTrainingContact.Id
        ];

        Assert.isTrue(testTrainingContact.Contact_Email_for_GetFeedback__c.endsWith('.invalid'),'Associated_Training_Contacts__c.Contact_Email_for_GetFeedback__c is invalidated');
        Assert.isTrue(testTrainingContact.Survey_Resend_Email_for_GetFeedback__c.endsWith('.invalid'),'Associated_Training_Contacts__c.Survey_Resend_Email_for_GetFeedback__c is invalidated');

        testPortalAccess = [
            SELECT 
                Email__c,
                Unique_Email__c
            FROM Portal_Access__c
            WHERE Id = :testPortalAccess.Id
        ];

        Assert.isTrue(testPortalAccess.Email__c.endsWith('.invalid'),'Portal_Access__c.Email__c is invalidated');
        Assert.isTrue(testPortalAccess.Unique_Email__c.endsWith('.invalid'),'Portal_Access__c.Unique_Email__c is invalidated');
    }
}