force-app/main/default/objects/Account/fields/BC_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>BC_Sync_Status__c</fullName>
    <description>Integration Status of record with Business Central</description>
    <inlineHelpText>Integration Status of record with Business Central</inlineHelpText>
    <label>BC Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BC_Synced__c.field-meta.xml
<CustomField>
    <fullName>BC_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if record is synced to BC system</description>
    <inlineHelpText>Record has been synced to Business Central</inlineHelpText>
    <label>BC Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NET 10</fullName>
            </value>
            <value>
                <fullName>NET 15</fullName>
            </value>
            <value>
                <fullName>NET 30</fullName>
            </value>
            <value>
                <fullName>NET 30 10D</fullName>
            </value>
            <value>
                <fullName>NET 45</fullName>
            </value>
            <value>
                <fullName>NET 60</fullName>
            </value>
            <value>
                <fullName>NET 75</fullName>
            </value>
            <value>
                <fullName>NET 90</fullName>
            </value>
            <value>
                <fullName>RECEIPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <inlineHelpText>RESELLER (Currently only Baker &amp; Taylor)
SERVICE (Currently only Microsoft)</inlineHelpText>
    <label>Price Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADKAR</fullName>
            </value>
            <value>
                <fullName>COMPLETE</fullName>
            </value>
            <value>
                <fullName>ECM</fullName>
            </value>
            <value>
                <fullName>MANAGER</fullName>
            </value>
            <value>
                <fullName>OCC</fullName>
            </value>
            <value>
                <fullName>AFFILIATE</fullName>
            </value>
            <value>
                <fullName>AFFTIER2</fullName>
            </value>
            <value>
                <fullName>ATP</fullName>
            </value>
            <value>
                <fullName>ATPTIER2</fullName>
            </value>
            <value>
                <fullName>RESELLER</fullName>
            </value>
            <value>
                <fullName>SERVICE</fullName>
            </value>
            <value>
                <fullName>PILOT</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>STDDISC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountBCSyncFilterTest.cls
@isTest
private class AccountBCSyncFilterTest {

    private static final Integer RECORD_COUNT = 200;
    private static final String TEST_NAME = 'Test Name';
    private static final String TEST_NAME_OLD = 'Test Name Old';
    private static final String TEST_PAYMENT_TERMS = 'NET 30';
    private static final String TEST_PAYMENT_TERMS_OLD = 'NET 45';
    private static final String TEST_PRICE_GROUP = 'ADKAR';
    private static final String TEST_PRICE_GROUP_OLD = 'ECM';
    private static final String BC_INSTANCE_US = 'Business_Central_US';

    @isTest static void filterRecords_noChange_returnEmpty(){
        List<Account> tLstAccts = new List<Account>();

        for(Integer i=0; i < RECORD_COUNT; i++){
            tLstAccts.add(new Account(
                Id = new TestUtils().generateDummyId(Account.SObjectType)
                , BC_Sync_Status__c = null
                , Name = TEST_NAME
                , Payment_Terms__c = TEST_PAYMENT_TERMS
                , Price_Group__c = TEST_PRICE_GROUP
                , BC_Synced__c = false
                , BC_Synced_Instances__c = null
            ));
        }

        Map<Id, Account> tMapOldAccts = new Map<Id, Account>(tLstAccts.deepClone(true));

        List<Account> rLstAccts;

        Test.startTest();

        rLstAccts = new AccountBCSyncFilter().filterRecords(tLstAccts, tMapOldAccts);

        Test.stopTest();

        System.assertEquals(0, rLstAccts.size()
            , 'When sync status does not change and record is not synced, no accounts should be returned');
    }

    @isTest static void filterRecords_notSyncedChangeToPendingSync_returnAll(){
        List<Account> tLstAccts = new List<Account>();

        for(Integer i=0; i < RECORD_COUNT; i++){
            tLstAccts.add(new Account(
                Id = new TestUtils().generateDummyId(Account.SObjectType)
                , BC_Sync_Status__c = AccountBCSyncFilter.STATUS_PENDING_SYNC
                , Name = TEST_NAME
                , Payment_Terms__c = TEST_PAYMENT_TERMS
                , Price_Group__c = TEST_PRICE_GROUP
                , BC_Synced__c = false
                , BC_Synced_Instances__c = null
            ));
        }

        Map<Id, Account> tMapOldAccts = new Map<Id, Account>(tLstAccts.deepClone(true));
        for(Account oldAcct : tMapOldAccts.values()){
            oldAcct.BC_Sync_Status__c = null;
        }

        List<Account> rLstAccts;

        Test.startTest();

        rLstAccts = new AccountBCSyncFilter().filterRecords(tLstAccts, tMapOldAccts);

        Test.stopTest();

        System.assertEquals(tLstAccts.size(), rLstAccts.size()
            , 'When sync status is changed to Pending Sync, all accounts should be returned');
    }

    @isTest static void filterRecords_syncedChangeToName_returnAll(){
        List<Account> tLstAccts = new List<Account>();

        for(Integer i=0; i < RECORD_COUNT; i++){
            tLstAccts.add(new Account(
                Id = new TestUtils().generateDummyId(Account.SObjectType)
                , BC_Sync_Status__c = AccountBCSyncFilter.STATUS_PENDING_SYNC
                , Name = TEST_NAME
                , Payment_Terms__c = TEST_PAYMENT_TERMS
                , Price_Group__c = TEST_PRICE_GROUP
                , BC_Synced__c = true
                , BC_Synced_Instances__c = BC_INSTANCE_US
            ));
        }

        Map<Id, Account> tMapOldAccts = new Map<Id, Account>(tLstAccts.deepClone(true));
        for(Account oldAcct : tMapOldAccts.values()){
            oldAcct.Name = TEST_NAME_OLD;
        }

        List<Account> rLstAccts;

        Test.startTest();

        rLstAccts = new AccountBCSyncFilter().filterRecords(tLstAccts, tMapOldAccts);

        Test.stopTest();

        System.assertEquals(tLstAccts.size(), rLstAccts.size()
            , 'When records are synced and name is changed, all accounts should be returned');
    }

    @isTest static void filterRecords_syncedChangeToPaymentTerms_returnAll(){
        List<Account> tLstAccts = new List<Account>();

        for(Integer i=0; i < RECORD_COUNT; i++){
            tLstAccts.add(new Account(
                Id = new TestUtils().generateDummyId(Account.SObjectType)
                , BC_Sync_Status__c = AccountBCSyncFilter.STATUS_PENDING_SYNC
                , Name = TEST_NAME
                , Payment_Terms__c = TEST_PAYMENT_TERMS
                , Price_Group__c = TEST_PRICE_GROUP
                , BC_Synced__c = true
                , BC_Synced_Instances__c = BC_INSTANCE_US
            ));
        }

        Map<Id, Account> tMapOldAccts = new Map<Id, Account>(tLstAccts.deepClone(true));
        for(Account oldAcct : tMapOldAccts.values()){
            oldAcct.Payment_Terms__c = TEST_PAYMENT_TERMS_OLD;
        }

        List<Account> rLstAccts;

        Test.startTest();

        rLstAccts = new AccountBCSyncFilter().filterRecords(tLstAccts, tMapOldAccts);

        Test.stopTest();

        System.assertEquals(tLstAccts.size(), rLstAccts.size()
            , 'When records are synced and payment terms are changed, all accounts should be returned');
    }

    @isTest static void filterRecords_syncedChangeToPriceGroup_returnAll(){
        List<Account> tLstAccts = new List<Account>();

        for(Integer i=0; i < RECORD_COUNT; i++){
            tLstAccts.add(new Account(
                Id = new TestUtils().generateDummyId(Account.SObjectType)
                , BC_Sync_Status__c = AccountBCSyncFilter.STATUS_PENDING_SYNC
                , Name = TEST_NAME
                , Payment_Terms__c = TEST_PAYMENT_TERMS
                , Price_Group__c = TEST_PRICE_GROUP
                , BC_Synced__c = true
                , BC_Synced_Instances__c = BC_INSTANCE_US
            ));
        }

        Map<Id, Account> tMapOldAccts = new Map<Id, Account>(tLstAccts.deepClone(true));
        for(Account oldAcct : tMapOldAccts.values()){
            oldAcct.Price_Group__c = TEST_PRICE_GROUP_OLD;
        }

        List<Account> rLstAccts;

        Test.startTest();

        rLstAccts = new AccountBCSyncFilter().filterRecords(tLstAccts, tMapOldAccts);

        Test.stopTest();

        System.assertEquals(tLstAccts.size(), rLstAccts.size()
            , 'When records are synced and price group is changed, all accounts should be returned');
    }
}