force-app/main/default/objects/Account/fields/BC_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>BC_Sync_Status__c</fullName>
    <description>Integration Status of record with Business Central</description>
    <inlineHelpText>Integration Status of record with Business Central</inlineHelpText>
    <label>BC Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NET 10</fullName>
            </value>
            <value>
                <fullName>NET 15</fullName>
            </value>
            <value>
                <fullName>NET 30</fullName>
            </value>
            <value>
                <fullName>NET 30 10D</fullName>
            </value>
            <value>
                <fullName>NET 45</fullName>
            </value>
            <value>
                <fullName>NET 60</fullName>
            </value>
            <value>
                <fullName>NET 75</fullName>
            </value>
            <value>
                <fullName>NET 90</fullName>
            </value>
            <value>
                <fullName>RECEIPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Group__c.field-meta.xml
<CustomField>
    <fullName>Price_Group__c</fullName>
    <inlineHelpText>RESELLER (Currently only Baker &amp; Taylor)
SERVICE (Currently only Microsoft)</inlineHelpText>
    <label>Price Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADKAR</fullName>
            </value>
            <value>
                <fullName>COMPLETE</fullName>
            </value>
            <value>
                <fullName>ECM</fullName>
            </value>
            <value>
                <fullName>MANAGER</fullName>
            </value>
            <value>
                <fullName>OCC</fullName>
            </value>
            <value>
                <fullName>AFFILIATE</fullName>
            </value>
            <value>
                <fullName>AFFTIER2</fullName>
            </value>
            <value>
                <fullName>ATP</fullName>
            </value>
            <value>
                <fullName>ATPTIER2</fullName>
            </value>
            <value>
                <fullName>RESELLER</fullName>
            </value>
            <value>
                <fullName>SERVICE</fullName>
            </value>
            <value>
                <fullName>PILOT</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>STDDISC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountBCSyncFilter.cls
/**
 * @author CloudMasonry
 * @date 2021
 * @group Filter
 * @description Filters Account Records for processing by AccountBCSyncCalloutService
 */
public with sharing class AccountBCSyncFilter {

    @testVisible
    private static final String STATUS_PENDING_SYNC = 'Pending Sync';

    public List<Account> filterRecords(List<Account> lstNewRecords, Map<Id, Account> mapOldRecords) {
        List<Account> filteredAccts = new List<Account>();
        
        for (Account acct : lstNewRecords) {
            Account oldacct = mapOldRecords.get(acct.Id);

            if ((acct.BC_Sync_Status__c != oldacct.BC_Sync_Status__c
                && acct.BC_Sync_Status__c == STATUS_PENDING_SYNC
                )
                || 
                    (acct.BC_Synced_Instances__c != null
                    && (acct.Name != oldacct.Name
                        || acct.Payment_Terms__c != oldacct.Payment_Terms__c
                        || acct.Price_Group__c != oldacct.Price_Group__c)
                    )) {

                filteredAccts.add(acct);
            }
        }
        
        return filteredAccts;
    }
}