force-app/main/default/objects/Account/fields/BC_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>BC_Sync_Status__c</fullName>
    <description>Integration Status of record with Business Central</description>
    <inlineHelpText>Integration Status of record with Business Central</inlineHelpText>
    <label>BC Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BC_Synced__c.field-meta.xml
<CustomField>
    <fullName>BC_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if record is synced to BC system</description>
    <inlineHelpText>Record has been synced to Business Central</inlineHelpText>
    <label>BC Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAV_Customer__c.field-meta.xml
<CustomField>
    <fullName>NAV_Customer__c</fullName>
    <label>NAV Customer #</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BC_Integration_Config__mdt/BC_Integration_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for each Business Central Integration</description>
    <label>BC Integration Config</label>
    <pluralLabel>BC Integration Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/BC_Integration_Config__mdt/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
                <default>true</default>
                <label>ANZ</label>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BC_Integration_Config__mdt/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <inlineHelpText>Business Central Integration - should be the last value in the URI path</inlineHelpText>
    <label>Integration Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SFContactEntries</fullName>
                <default>true</default>
                <label>SFContactEntries</label>
            </value>
            <value>
                <fullName>SFCustomerEntries</fullName>
            </value>
            <value>
                <fullName>SFOpportunityEntries</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BC_Integration_Config__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <inlineHelpText>Named Credential for the web service for authentication</inlineHelpText>
    <label>Named Credential</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business_Central_US</fullName>
                <default>true</default>
                <label>Business_Central_US</label>
            </value>
            <value>
                <fullName>Business_Central_CAN</fullName>
            </value>
            <value>
                <fullName>Business_Central_ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BC_Integration_Config__mdt/fields/URI_Path__c.field-meta.xml
<CustomField>
    <fullName>URI_Path__c</fullName>
    <inlineHelpText>URI path of the web service endpoint. Appends to the URL in the Named Credential.</inlineHelpText>
    <label>URI Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the error for reporting</description>
    <inlineHelpText>Category of the error for reporting</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>BigObjectException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
            <value>
                <fullName>SObjectException</fullName>
            </value>
            <value>
                <fullName>StringException</fullName>
            </value>
            <value>
                <fullName>TypeException</fullName>
            </value>
            <value>
                <fullName>VisualforceException</fullName>
            </value>
            <value>
                <fullName>XmlException</fullName>
            </value>
            <value>
                <fullName>CalloutResponse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BC_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>BC_Sync_Status__c</fullName>
    <label>BC Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BC_Synced__c.field-meta.xml
<CustomField>
    <fullName>BC_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BC Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dropship__c.field-meta.xml
<CustomField>
    <fullName>Dropship__c</fullName>
    <label>Dropship from:</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <formula>Owner.CommunityNickname</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesperson Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sell_To__c.field-meta.xml
<CustomField>
    <fullName>Sell_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sell To:</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Sell To:)</relationshipLabel>
    <relationshipName>Sell_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/BC_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>BC_Sync_Status__c</fullName>
    <description>Sync Status of record with Business Central. Sync is driven from the Opportunity.</description>
    <inlineHelpText>Sync Status of record with Business Central. Sync is driven from the Opportunity.</inlineHelpText>
    <label>BC Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/BC_Synced_Instances__c.field-meta.xml
<CustomField>
    <fullName>BC_Synced_Instances__c</fullName>
    <label>BC Synced Instances</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BC_Synced_Instances_c</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>cont-ih</fullName>
                <label>Content: Instructor Hub</label>
            </value>
            <value>
                <fullName>cont-rh</fullName>
                <label>Content: Research Hub</label>
            </value>
            <value>
                <fullName>cont-elrn-en</fullName>
                <label>Content: English Elearning</label>
            </value>
            <value>
                <fullName>cont-elrn-pt</fullName>
                <label>Content: Portugese Elearning</label>
            </value>
            <value>
                <fullName>cont-elrn-es</fullName>
                <label>Content: Spanish Elearning</label>
            </value>
            <value>
                <fullName>cont-elrn-fr</fullName>
                <label>Content: French Elearning</label>
            </value>
            <value>
                <fullName>cont-advtrk</fullName>
                <label>Content: Advanced Tracks</label>
            </value>
            <value>
                <fullName>cont</fullName>
                <label>Other Content</label>
            </value>
            <value>
                <fullName>lgy</fullName>
                <label>Legacy Apps</label>
            </value>
            <value>
                <fullName>lgy-rsrc</fullName>
                <label>Legacy Resources</label>
            </value>
            <value>
                <fullName>lgy-web</fullName>
                <label>Legacy Webinars</label>
            </value>
            <value>
                <fullName>other</fullName>
                <label>Other Resources</label>
            </value>
            <value>
                <fullName>cont-kh</fullName>
                <label>Content: Knowledge Hub</label>
            </value>
            <value>
                <fullName>apps</fullName>
                <label>Apps</label>
            </value>
            <value>
                <fullName>bundles</fullName>
                <label>Bundles</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Dropship_Only__c.field-meta.xml
<CustomField>
    <fullName>Dropship_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select if product should only go to Dropshipment BC Instance for Dropship Orders. Product will not go to non-dropship BC Instance. Does not impact Orders that do not have a dropshipment.</inlineHelpText>
    <label>Dropship Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/BC_Synced_Instances_c.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business_Central_ANZ</fullName>
        <label>Business Central ANZ</label>
    </customValue>
    <customValue>
        <fullName>Business_Central_CAN</fullName>
        <label>Business Central CAN</label>
    </customValue>
    <customValue>
        <fullName>Business_Central_US</fullName>
        <label>Business Central US</label>
    </customValue>
    <description>BC Regions</description>
    <masterLabel>BC Synced Instances</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityBCSyncCalloutServiceTest.cls
@isTest
private class OpportunityBCSyncCalloutServiceTest {

    private static final String BC_INSTANCE_US = 'Business_Central_US';
    private static final String BC_INSTANCE_CAN = 'Business_Central_CAN';
    private static final String BC_INSTANCE_ANZ = 'Business_Central_ANZ';
    private static final String DIVISION_US = 'USA';
    private static final String DIVISION_CAN = 'CAN';
    private static final String DIVISION_INVALID = 'INVALID';


    private static User ADMIN_USER {
        get { 
            if(ADMIN_USER == null){
                ADMIN_USER = [SELECT Id
                              FROM User
                              WHERE Profile.PermissionsModifyAllData = true
                              AND Profile.PermissionsManageUsers = true
                              AND IsActive = true LIMIT 1];
            }
            return ADMIN_USER;
        }
        set;
    }

    private static Profile profileWithModifyAll {
        get {
            if(profileWithModifyAll == null){
                profileWithModifyAll = [SELECT Id FROM Profile WHERE Profile.PermissionsModifyAllData = true LIMIT 1];
            }
        return profileWithModifyAll;
        }
        set;
    }

    private static Date DATE_TODAY {
        get {
            if(DATE_TODAY == null){
                DATE_TODAY = Date.today();
            }
            return DATE_TODAY;
        }
        set;
    }

    @TestSetup
    static void setupData(){

        User testUser = buildUser(DIVISION_US);
        insert testUser;

        AccountTriggerHandler.byPass = true;
        Account acct = buildAccount(testUser);
        insert acct;
        AccountTriggerHandler.byPass = false;

        Product2 tProd = buildProduct();

        Product2 tProdDropShip = buildProduct();
        tProdDropShip.Dropship_Only__c = true;

        List<Product2> lstProds = new List<Product2>();
        lstProds.add(tProd);
        lstProds.add(tProdDropShip);
        insert lstProds;

        PricebookEntry tPBE = buildPriceBookEntry(tProd);
        PricebookEntry tPBEDS = buildPriceBookEntry(tProdDropShip);
        
        List<PricebookEntry> lstPBEs = new List<PricebookEntry>();
        lstPBEs.add(tPBE);
        lstPBEs.add(tPBEDS);

        insert lstPBEs;

        Opportunity tOpp = buildOpportunity(acct, testUser);
        insert tOpp;

        OpportunityLineItem tOppLI = buildOppLineItem(tOpp, tPBE);
        OpportunityLineItem tOppLIDS = buildOppLineItem(tOpp, tPBEDS);
        List<OpportunityLineItem> lstOLIs = new List<OpportunityLineItem>();
        lstOLIs.add(tOppLI);
        lstOLIs.add(tOppLIDS);
        insert lstOLIs;
    }

    private static User buildUser(String strDivision){
        return new User(
            ProfileId = profileWithModifyAll.Id
            , LastName = 'last'
            , Email = 'test@example.com'
            , Username = 'proscitestUser' + System.currentTimeMillis() + '@prosci.com.unittest'
            , CompanyName = 'TEST'
            , Title = 'title'
            , Alias = 'alias'
            , TimeZoneSidKey = 'America/Los_Angeles'
            , EmailEncodingKey = 'UTF-8'
            , LanguageLocaleKey = 'en_US'
            , LocaleSidKey = 'en_US'
            , Division = strDivision
        );
    }

    private static Account buildAccount(User testUser){
        return new Account(
            Name = 'Test Acc'
            , NAV_Customer__c = '123'
            , BillingStreet = '500 Main St'
            , BillingState = 'IL'
            , BillingCity = 'Chicago'
            , BillingCountry = 'IL'
            , BillingPostalCode = '60654'
            , Phone = '14245533535'
            , Fax = '44553535'
            , BC_Synced__c = true
            , BC_Synced_Instances__c = BC_INSTANCE_US
            , OwnerId = testUser.Id
        );
    }

    private static Opportunity buildOpportunity(Account acct, User testUser){
        return new Opportunity(
            Name = 'Test Oppo'
            , StageName = 'License Confirmed'
            , CloseDate = DATE_TODAY
            , LeadSource = 'Conference'
            , Shipment_Date__c = DATE_TODAY
            , Pricebook2Id = Test.getStandardPricebookId()
            , OwnerId = testUser.Id
            , AccountId = acct.Id
            , Sell_To__c = acct.Id
        );
    }

    private static Opportunity buildOpportunityMock(String strOwnerDivision){
        User testUser = buildUser(strOwnerDivision);
        testUser.Id = new TestUtils().generateDummyId(User.SObjectType);

        Account tAcct = buildAccount(testUser);
        tAcct.Id = new TestUtils().generateDummyId(Account.SObjectType);

        Opportunity tOpp = buildOpportunity(tAcct, testUser);
        tOpp = (Opportunity)writeFormulaFields(tOpp, new Map<String, Object>{
            'Salesperson_Code__c' => 'SPC'
        });
        tOpp.Owner = testUser;
        tOpp.Account = tAcct;
        tOpp.Id = new TestUtils().generateDummyId(Opportunity.SObjectType);
        return tOpp;
    }

    private static Product2 buildProduct(){
        return new Product2(
            Name = 'Test Product'
            , ProductCode = 'TEST_PRODUCT'
        );
    }

    private static PricebookEntry buildPriceBookEntry(Product2 prod){
        return new PricebookEntry(
            Product2Id = prod.Id
            , Pricebook2Id = Test.getStandardPricebookId()
            , UnitPrice = 0
            , IsActive = true
        );
    }

    private static OpportunityLineItem buildOppLineItem(Opportunity opp, PricebookEntry pbe){
        return new OpportunityLineItem(
            OpportunityId = opp.Id
            , PriceBookEntryId = pbe.Id
            , UnitPrice = 0
            , Quantity  = 1
        );
    }

    private static OpportunityLineItem buildOppLineItemMock(Opportunity opp, Boolean isDropShip){
        Product2 prod = buildProduct();
        prod.Id = new TestUtils().generateDummyId(Product2.SObjectType);
        prod.Dropship_Only__c = isDropShip;

        PricebookEntry pbe = buildPriceBookEntry(prod);
        pbe.Id = new TestUtils().generateDummyId(PricebookEntry.SObjectType);
        OpportunityLineItem oppLI = new OpportunityLineItem(
            OpportunityId = opp.Id
            , PriceBookEntryId = pbe.Id
            , UnitPrice = 0
            , Quantity  = 1
        );
        oppLI.Product2 = prod;
        oppLI.Id = new TestUtils().generateDummyId(OpportunityLineItem.SObjectType);
        return oppLI;
    }

    private static SObject buildChildRelationship(SObject sObj, List<SObject> lstChildren, String relationshipName){
        Map<String, Object> mapObj = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(sObj));
        Map<String, Object> childMap = new Map<String, Object>();
        childMap.put('records', lstChildren);
        childMap.put('done', true);
        childMap.put('totalSize', lstChildren.size());
        mapObj.put(relationshipName, childMap);
        return (SObject)JSON.deserialize(JSON.serialize(mapObj), SObject.class);
    }

    private static SObject writeFormulaFields(SObject sObj, Map<String, Object> mapFormulaKeyValues){
        Map<String, Object> mapObj = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(sObj));
        for(String key : mapFormulaKeyValues.keySet()){
            mapObj.put(key, mapFormulaKeyValues.get(key));
        }
        return (SObject)JSON.deserialize(JSON.serialize(mapObj), SObject.class);
    }


    private static Map<String, BC_Integration_Config__mdt> buildIntegrationConfigMetadata(){
        Map<String, BC_Integration_Config__mdt> mapInstanceIntegrationConfig = new Map<String, BC_Integration_Config__mdt>();

        mapInstanceIntegrationConfig.put(BC_INSTANCE_US, new BC_Integration_Config__mdt(
            Active__c = true                
            , Division__c = 'USA'
            , Integration_Name__c = AccountBCSyncCalloutService.INTEGRATION_CONFIG_NAME
            , Named_Credential__c = BC_INSTANCE_US
            , URI_Path__c = '/SFOpportunityEntries'
        ));

        mapInstanceIntegrationConfig.put(BC_INSTANCE_CAN, new BC_Integration_Config__mdt(
            Active__c = true                
            , Division__c = 'CAN'
            , Integration_Name__c = AccountBCSyncCalloutService.INTEGRATION_CONFIG_NAME
            , Named_Credential__c = BC_INSTANCE_CAN
            , URI_Path__c = '/SFOpportunityEntries'
        ));

        mapInstanceIntegrationConfig.put(BC_INSTANCE_ANZ, new BC_Integration_Config__mdt(
            Active__c = true                
            , Division__c = 'ANZ'
            , Integration_Name__c = AccountBCSyncCalloutService.INTEGRATION_CONFIG_NAME
            , Named_Credential__c = BC_INSTANCE_ANZ
            , URI_Path__c = '/SFOpportunityEntries'
        ));
        return mapInstanceIntegrationConfig;
    }

    @isTest static void execute_statusCode201(){

        Set<Id> tSetIds = new Map<Id, Opportunity>([SELECT Id FROM Opportunity]).keySet();

        Test.setMock(HttpCalloutMock.class, new PushToBcGenericMock(201));

        Test.startTest();

        new OpportunityBCSyncCalloutService(tSetIds).execute(); 

        Test.stopTest();

        List<Error_Log__c> rLstLogs = [SELECT Id FROM Error_Log__c];
        System.assertEquals(0, rLstLogs.size(), 'No Error Logs should be created');
        List<Opportunity> rLstOpps = [SELECT Id, BC_Synced__c, BC_Sync_Status__c FROM Opportunity];
        List<OpportunityLineItem> rLstOppItems = [SELECT Id, BC_Sync_Status__c, BC_Synced_Instances__c FROM OpportunityLineItem];
        System.assertNotEquals(0, rLstOpps.size());
        System.assertNotEquals(0, rLstOppItems.size());
        for(Opportunity opp : rLstOpps){
            System.assertEquals(OpportunityBCSyncCalloutService.STATUS_SYNCED, opp.BC_Sync_Status__c);
        }
        for(OpportunityLineItem oppItem : rLstOppItems){
            System.assertEquals(BC_INSTANCE_US, oppItem.BC_Synced_Instances__c);
            System.assertEquals(OpportunityBCSyncCalloutService.STATUS_SYNCED, oppItem.BC_Sync_Status__c);
        }
    }

    @IsTest static void executeMock_orderToUS_StatusCode201() {

        Set<Id> tSetIds = new Set<Id>();

        List<Opportunity> tLstOpps = new List<Opportunity>();
        Opportunity tOpp = buildOpportunityMock(DIVISION_US);
        tOpp.Dropship__c = null;

        List<OpportunityLineItem> lstOLIs = new List<OpportunityLineItem>();
        OpportunityLineItem tOppLI = buildOppLineItemMock(tOpp, false);
        OpportunityLineItem tOppLI2 = buildOppLineItemMock(tOpp, false);
        lstOLIs.add(tOppLI);
        lstOLIs.add(tOppLI2);

        tOpp = (Opportunity)buildChildRelationship(tOpp, lstOLIs, 'OpportunityLineItems');
        tLstOpps.add(tOpp);
        tSetIds.add(tOpp.Id);
        
        Map<String, Object> mapMethodReturns = new Map<String, Object>();
        mapMethodReturns.put('getIntegrationConfigMap', buildIntegrationConfigMetadata());
        mapMethodReturns.put('getOpportunities', tLstOpps);


        BCSyncDAO mockServiceDAO = (BCSyncDAO)Test.createStub(BCSyncDAO.Class, new TestUtils_TestMock(mapMethodReturns));
        SObjectDAO mockSObjDAO = (SOBjectDAO)Test.createStub(SObjectDAO.Class, new TestUtils_TestMock());

        Test.setMock(HttpCalloutMock.class, new PushToBcGenericMock(201));

        Test.startTest();

        OpportunityBCSyncCalloutService calloutService = new OpportunityBCSyncCalloutService(tSetIds, mockServiceDAO, mockSObjDAO);
        calloutService.execute();

        Test.stopTest();

        System.assertEquals(0, calloutService.lstErrorsToInsert.size(), 'No Error Logs should be instantiated');

        List<Opportunity> rListOpps = calloutService.lstOppsToUpdate;
        List<OpportunityLineItem> rLstOppProds = calloutService.lstOppLinesToUpdate;

        for(Opportunity opp : rListopps){

            System.assertEquals(true, opp.BC_Synced__c);
        }

        for(OpportunityLineItem oppProd : rLstOppProds){
            
            System.assertEquals(OpportunityBCSyncCalloutService.STATUS_SYNCED, oppProd.BC_Sync_Status__c);
            System.assertEquals(BC_INSTANCE_US, oppProd.BC_Synced_Instances__c, 'Each successfully synced instance should be set on record');
        }
    }

    @IsTest static void executeMock_orderToCAN_dropshipToUS_StatusCode201() {

        Set<Id> tSetIds = new Set<Id>();

        List<Opportunity> tLstOpps = new List<Opportunity>();
        Opportunity tOpp = buildOpportunityMock(DIVISION_CAN);
        tOpp.Dropship__c = DIVISION_US;

        List<OpportunityLineItem> lstOLIs = new List<OpportunityLineItem>();
        OpportunityLineItem tOppLI = buildOppLineItemMock(tOpp, false);
        OpportunityLineItem tOppLIDropShip = buildOppLineItemMock(tOpp, true);
        lstOLIs.add(tOppLI);
        lstOLIs.add(tOppLIDropShip);

        tOpp = (Opportunity)buildChildRelationship(tOpp, lstOLIs, 'OpportunityLineItems');
        tLstOpps.add(tOpp);
        tSetIds.add(tOpp.Id);
        
        Map<String, Object> mapMethodReturns = new Map<String, Object>();
        mapMethodReturns.put('getIntegrationConfigMap', buildIntegrationConfigMetadata());
        mapMethodReturns.put('getOpportunities', tLstOpps);


        BCSyncDAO mockServiceDAO = (BCSyncDAO)Test.createStub(BCSyncDAO.Class, new TestUtils_TestMock(mapMethodReturns));
        SObjectDAO mockSObjDAO = (SOBjectDAO)Test.createStub(SObjectDAO.Class, new TestUtils_TestMock());

        Test.setMock(HttpCalloutMock.class, new PushToBcGenericMock(201));

        Test.startTest();

        OpportunityBCSyncCalloutService calloutService = new OpportunityBCSyncCalloutService(tSetIds, mockServiceDAO, mockSObjDAO);
        calloutService.execute();

        Test.stopTest();

        System.assertEquals(0, calloutService.lstErrorsToInsert.size(), 'No Error Logs should be instantiated');

        List<Opportunity> rListOpps = calloutService.lstOppsToUpdate;
        List<OpportunityLineItem> rLstOppProds = calloutService.lstOppLinesToUpdate;

        for(Opportunity opp : rListopps){

            System.assertEquals(true, opp.BC_Synced__c);
        }

        Boolean standardProd = false;
        Boolean dropShipProd = false;

        Set<String> setExpectedInstances = new Set<String>{
            BC_INSTANCE_US
            , BC_INSTANCE_CAN
        };

        for(OpportunityLineItem oppProd : rLstOppProds){
            
            System.assertEquals(OpportunityBCSyncCalloutService.STATUS_SYNCED, oppProd.BC_Sync_Status__c);

            if(oppProd.Id == tOppLI.Id){
                

                System.assertNotEquals(null, oppProd.BC_Synced_Instances__c, 'Non Dropship products should go to both Dropship and Division Instance');
                Set<String> setActualInstances = new Set<String>();
                setActualInstances.addAll(oppProd.BC_Synced_Instances__c.split(';'));
                System.assertEquals(setExpectedInstances, setActualInstances, 'Non Dropship products should go to both Dropship and Division Instance');

                standardProd = true;
            } else if(oppProd.Id == tOppLIDropShip.Id){
                System.assertEquals(BC_INSTANCE_US, oppProd.BC_Synced_Instances__c, 'Dropship products should only go to both Dropship Instance');

                dropShipProd = true;
            }
        }

        System.assert(standardProd, 'Standard Product Opportunity Line Item should be asserted against');
        System.assert(dropShipProd, 'Dropship Product Opportunity Line Item should be asserted against');
    }

    @IsTest static void executeMock_orderToInvalid_InvalidConfigException() {

        Set<Id> tSetIds = new Set<Id>();

        List<Opportunity> tLstOpps = new List<Opportunity>();
        Opportunity tOpp = buildOpportunityMock(DIVISION_INVALID);
        tOpp.Dropship__c = null;

        List<OpportunityLineItem> lstOLIs = new List<OpportunityLineItem>();
        OpportunityLineItem tOppLI = buildOppLineItemMock(tOpp, false);
        OpportunityLineItem tOppLI2 = buildOppLineItemMock(tOpp, false);
        lstOLIs.add(tOppLI);
        lstOLIs.add(tOppLI2);

        tOpp = (Opportunity)buildChildRelationship(tOpp, lstOLIs, 'OpportunityLineItems');
        tLstOpps.add(tOpp);
        tSetIds.add(tOpp.Id);
        
        Map<String, Object> mapMethodReturns = new Map<String, Object>();
        mapMethodReturns.put('getIntegrationConfigMap', buildIntegrationConfigMetadata());
        mapMethodReturns.put('getOpportunities', tLstOpps);


        BCSyncDAO mockServiceDAO = (BCSyncDAO)Test.createStub(BCSyncDAO.Class, new TestUtils_TestMock(mapMethodReturns));
        SObjectDAO mockSObjDAO = (SOBjectDAO)Test.createStub(SObjectDAO.Class, new TestUtils_TestMock());

        Test.setMock(HttpCalloutMock.class, new PushToBcGenericMock(201));

        CustomMetadataException mtdEx;

        Test.startTest();

        try {
            OpportunityBCSyncCalloutService calloutService = new OpportunityBCSyncCalloutService(tSetIds, mockServiceDAO, mockSObjDAO);
            calloutService.execute();
        } catch (CustomMetadataException ex){
            mtdEx = ex;
        }

        Test.stopTest();

        System.assertNotEquals(null, mtdEx);
        System.assertEquals(OpportunityBCSyncCalloutService.EXCEPTION_MISSING_CUSTOM_METADATA_DIVISION + DIVISION_INVALID, mtdEx.getMessage());
    }

    @IsTest static void executeMock_orderToCAN_DropShipToInvalid_InvalidConfigException() {

        Set<Id> tSetIds = new Set<Id>();

        List<Opportunity> tLstOpps = new List<Opportunity>();
        Opportunity tOpp = buildOpportunityMock(DIVISION_CAN);
        tOpp.Dropship__c = DIVISION_INVALID;

        List<OpportunityLineItem> lstOLIs = new List<OpportunityLineItem>();
        OpportunityLineItem tOppLI = buildOppLineItemMock(tOpp, false);
        OpportunityLineItem tOppLI2 = buildOppLineItemMock(tOpp, false);
        lstOLIs.add(tOppLI);
        lstOLIs.add(tOppLI2);

        tOpp = (Opportunity)buildChildRelationship(tOpp, lstOLIs, 'OpportunityLineItems');
        tLstOpps.add(tOpp);
        tSetIds.add(tOpp.Id);
        
        Map<String, Object> mapMethodReturns = new Map<String, Object>();
        mapMethodReturns.put('getIntegrationConfigMap', buildIntegrationConfigMetadata());
        mapMethodReturns.put('getOpportunities', tLstOpps);


        BCSyncDAO mockServiceDAO = (BCSyncDAO)Test.createStub(BCSyncDAO.Class, new TestUtils_TestMock(mapMethodReturns));
        SObjectDAO mockSObjDAO = (SOBjectDAO)Test.createStub(SObjectDAO.Class, new TestUtils_TestMock());

        Test.setMock(HttpCalloutMock.class, new PushToBcGenericMock(201));

        CustomMetadataException mtdEx;

        Test.startTest();

        try {
            OpportunityBCSyncCalloutService calloutService = new OpportunityBCSyncCalloutService(tSetIds, mockServiceDAO, mockSObjDAO);
            calloutService.execute();
        } catch (CustomMetadataException ex){
            mtdEx = ex;
        }

        Test.stopTest();

        System.assertNotEquals(null, mtdEx);
        System.assertEquals(OpportunityBCSyncCalloutService.EXCEPTION_MISSING_CUSTOM_METADATA_DROPSHIP + DIVISION_INVALID, mtdEx.getMessage());
    }

    @isTest static void trigger_execute_statusCode201(){

        List<Opportunity> tLstOpps = [SELECT BC_Sync_Status__c FROM Opportunity];
        for(Opportunity opp : tLstOpps){
            opp.BC_Sync_Status__c = 'Pending Sync';
        }

        Test.setMock(HttpCalloutMock.class, new PushToBcGenericMock(201));

        Test.startTest();
 
        update tLstOpps;

        Test.stopTest();

        List<Error_Log__c> rLstLogs = [SELECT Id FROM Error_Log__c];
        System.assertEquals(0, rLstLogs.size(), 'No Error Logs should be created');
        List<Opportunity> rLstOpps = [SELECT Id, BC_Synced__c, BC_Sync_Status__c FROM Opportunity];
        List<OpportunityLineItem> rLstOppItems = [SELECT Id, BC_Sync_Status__c FROM OpportunityLineItem];
        System.assertNotEquals(0, rLstOpps.size());
        System.assertNotEquals(0, rLstOppItems.size());
        for(Opportunity opp : rLstOpps){
            System.assertEquals(true, opp.BC_Synced__c);
            System.assertEquals(OpportunityBCSyncCalloutService.STATUS_SYNCED, opp.BC_Sync_Status__c);
        }
        for(OpportunityLineItem oppItem : rLstOppItems){
            System.assertEquals(OpportunityBCSyncCalloutService.STATUS_SYNCED, oppItem.BC_Sync_Status__c);
        }
    }

    @isTest static void execute_statusCode400_calloutException(){

        Set<Id> tSetIds = new Map<Id, Opportunity>([SELECT Id FROM Opportunity]).keySet();

        Test.setMock(HttpCalloutMock.class, new PushToBcGenericMock(400));

        Test.startTest();

        new OpportunityBCSyncCalloutService(tSetIds).execute();

        Test.stopTest();

        List<Error_Log__c> rLstLogs = [SELECT Exception_Type__c, Category__c FROM Error_Log__c];
        System.assertNotEquals(0, rLstLogs.size(), 'An Error Log should be created to capture the error');
        for(Error_Log__c log : rLstLogs){
            System.assertEquals(new CalloutException().getTypeName(), log.Exception_Type__c);
            System.assertEquals(OpportunityBCSyncCalloutService.EXCEPTION_CATEGORY, log.Category__c);
        }
        List<Opportunity> rLstOpps = [SELECT Id, BC_Synced__c, BC_Sync_Status__c FROM Opportunity];
        List<OpportunityLineItem> rLstOppItems = [SELECT Id, BC_Sync_Status__c FROM OpportunityLineItem];
        System.assertNotEquals(0, rLstOpps.size());
        System.assertNotEquals(0, rLstOppItems.size());
        for(Opportunity opp : rLstOpps){
            System.assertEquals(false, opp.BC_Synced__c);
            System.assertEquals(OpportunityBCSyncCalloutService.STATUS_FAILED, opp.BC_Sync_Status__c);
        }
        for(OpportunityLineItem oppItem : rLstOppItems){
            System.assertNotEquals(OpportunityBCSyncCalloutService.STATUS_SYNCED, oppItem.BC_Sync_Status__c);
        }
    }

    @isTest static void execute_genericException(){

        Set<Id> tSetIds = new Map<Id, Opportunity>([SELECT Id FROM Opportunity]).keySet();

        Test.setMock(HttpCalloutMock.class, new PushToBcGenericMock(201).forceMockException());

        Test.startTest();

        new OpportunityBCSyncCalloutService(tSetIds).execute();

        Test.stopTest();

        List<Error_Log__c> rLstLogs = [SELECT Exception_Type__c, Category__c FROM Error_Log__c];
        System.assertNotEquals(0, rLstLogs.size(), 'An Error Log should be created to capture the error');
        for(Error_Log__c log : rLstLogs){
            System.assertEquals(new PushToBcGenericMock.MockException().getTypeName(), log.Exception_Type__c);
            System.assertEquals(OpportunityBCSyncCalloutService.EXCEPTION_CATEGORY, log.Category__c);
        }
        List<Opportunity> rLstOpps = [SELECT Id, BC_Synced__c, BC_Sync_Status__c FROM Opportunity];
        List<OpportunityLineItem> rLstOppItems = [SELECT Id, BC_Sync_Status__c FROM OpportunityLineItem];
        System.assertNotEquals(0, rLstOpps.size());
        System.assertNotEquals(0, rLstOppItems.size());
        for(Opportunity opp : rLstOpps){
            System.assertEquals(false, opp.BC_Synced__c);
            System.assertEquals(OpportunityBCSyncCalloutService.STATUS_FAILED, opp.BC_Sync_Status__c);
        }
        for(OpportunityLineItem oppItem : rLstOppItems){
            System.assertNotEquals(OpportunityBCSyncCalloutService.STATUS_SYNCED, oppItem.BC_Sync_Status__c);
        }
    }
}