force-app/main/default/objects/Contact/fields/BC_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>BC_Sync_Status__c</fullName>
    <label>BC Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/BC_Synced_Instances__c.field-meta.xml
<CustomField>
    <fullName>BC_Synced_Instances__c</fullName>
    <label>BC Synced Instances</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BC_Synced_Instances_c</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BC_Synced_Instances_c.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business_Central_ANZ</fullName>
        <label>Business Central ANZ</label>
    </customValue>
    <customValue>
        <fullName>Business_Central_CAN</fullName>
        <label>Business Central CAN</label>
    </customValue>
    <customValue>
        <fullName>Business_Central_US</fullName>
        <label>Business Central US</label>
    </customValue>
    <description>BC Regions</description>
    <masterLabel>BC Synced Instances</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactBCSyncFilter.cls
/**
 * @author CloudMasonry
 * @date 2021
 * @group Filter
 * @description Filters Contact Records for processing by ContactBCSyncCalloutService
 */
public with sharing class ContactBCSyncFilter {

    @testVisible
    private static final String STATUS_PENDING_SYNC = 'Pending Sync';

    public List<Contact> filterRecords (List<Contact> lstNewRecords, Map<Id, Contact> mapOldRecords) {
        List<Contact> filteredContacts = new List<Contact>();

        for (Contact con : lstNewRecords) {
            Contact oldRecord = mapOldRecords.get(con.Id);

            if ((con.BC_Sync_Status__c != oldRecord.BC_Sync_Status__c
                && con.BC_Sync_Status__c == STATUS_PENDING_SYNC)
                ||	(con.BC_Synced_Instances__c != null &&
                        (con.LastName != oldRecord.LastName
                        || con.FirstName != oldRecord.FirstName
                        || con.AccountId != oldRecord.AccountId
                        || con.Email != oldRecord.Email)
                )) {

                filteredContacts.add(con);
            }
        }

        return filteredContacts;
    }

}